ALTER TABLE [dbo].[ILOSCategory]  WITH CHECK ADD  CONSTRAINT [FK__ILOSCateg__Count__440B1D61] FOREIGN KEY([CountryID])
REFERENCES [dbo].[Country] ([ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ILOSCategory] CHECK CONSTRAINT [FK__ILOSCateg__Count__440B1D61]